[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "flexicodec"
version = "0.1.0"
description = "A Dynamic Neural Audio Codec for Low Frame Rates"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

dependencies = [
    "transformers>=4.30.0",
    "descript-audiotools>=0.7.2",
    "huggingface_hub[cli]",
    "easydict",
    "torch",
    "torchaudio",
    "hydra-core",
    "einops",
    "safetensors",
    "cached_path",
    "funasr",
]

[project.optional-dependencies]
tts = [
    "cached-path",
    "phonemizer",
    "openai-whisper",
    "f5_tts",
    "accelerate>=1.0",
    "datasets",
    "openai-whisper",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["flexicodec*"]

[tool.setuptools.package-data]
flexicodec = [
    "am.mvn",
    "conf/*.yaml",
]